TYPE=VIEW
query=select `insentif`.`mapping_insentif_detail`.`idmapping` AS `idmapping`,`insentif`.`mapping_insentif`.`tglmapping` AS `tglmapping`,`insentif`.`mapping_insentif_detail`.`idbarang_insentif` AS `idbarang_insentif`,`insentif`.`barang_insentif`.`idbarang` AS `idbarang`,`insentif`.`barang`.`namabarang` AS `namabarang`,`insentif`.`barang`.`jenis` AS `jenis`,`insentif`.`barang`.`satuan` AS `satuan`,`insentif`.`barang`.`hargajual` AS `hargajual`,`insentif`.`barang_insentif`.`targetqty_awal` AS `targetqty_awal`,`insentif`.`barang_insentif`.`targetqty_akhir` AS `targetqty_akhir`,`insentif`.`mapping_insentif_detail`.`bonus` AS `bonus`,`insentif`.`mapping_insentif_detail`.`qtyterjual` AS `qtyterjual` from (((`insentif`.`mapping_insentif_detail` join `insentif`.`mapping_insentif` on(`insentif`.`mapping_insentif_detail`.`idmapping` = `insentif`.`mapping_insentif`.`idmapping`)) join `insentif`.`barang_insentif` on(`insentif`.`mapping_insentif_detail`.`idbarang_insentif` = `insentif`.`barang_insentif`.`idbarang_insentif`)) join `insentif`.`barang` on(`insentif`.`barang_insentif`.`idbarang` = `insentif`.`barang`.`idbarang`))
md5=e79b45578b0c616f448e1b3ee57b9957
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2024-06-16 13:52:32
create-version=2
source=select `mapping_insentif_detail`.`idmapping` AS `idmapping`,`mapping_insentif`.`tglmapping` AS `tglmapping`,`mapping_insentif_detail`.`idbarang_insentif` AS `idbarang_insentif`,`barang_insentif`.`idbarang` AS `idbarang`,`barang`.`namabarang` AS `namabarang`,`barang`.`jenis` AS `jenis`,`barang`.`satuan` AS `satuan`,`barang`.`hargajual` AS `hargajual`,`barang_insentif`.`targetqty_awal` AS `targetqty_awal`,`barang_insentif`.`targetqty_akhir` AS `targetqty_akhir`,`mapping_insentif_detail`.`bonus` AS `bonus`,`mapping_insentif_detail`.`qtyterjual` AS `qtyterjual` from (((`mapping_insentif_detail` join `mapping_insentif` on(`mapping_insentif_detail`.`idmapping` = `mapping_insentif`.`idmapping`)) join `barang_insentif` on(`mapping_insentif_detail`.`idbarang_insentif` = `barang_insentif`.`idbarang_insentif`)) join `barang` on(`barang_insentif`.`idbarang` = `barang`.`idbarang`))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `insentif`.`mapping_insentif_detail`.`idmapping` AS `idmapping`,`insentif`.`mapping_insentif`.`tglmapping` AS `tglmapping`,`insentif`.`mapping_insentif_detail`.`idbarang_insentif` AS `idbarang_insentif`,`insentif`.`barang_insentif`.`idbarang` AS `idbarang`,`insentif`.`barang`.`namabarang` AS `namabarang`,`insentif`.`barang`.`jenis` AS `jenis`,`insentif`.`barang`.`satuan` AS `satuan`,`insentif`.`barang`.`hargajual` AS `hargajual`,`insentif`.`barang_insentif`.`targetqty_awal` AS `targetqty_awal`,`insentif`.`barang_insentif`.`targetqty_akhir` AS `targetqty_akhir`,`insentif`.`mapping_insentif_detail`.`bonus` AS `bonus`,`insentif`.`mapping_insentif_detail`.`qtyterjual` AS `qtyterjual` from (((`insentif`.`mapping_insentif_detail` join `insentif`.`mapping_insentif` on(`insentif`.`mapping_insentif_detail`.`idmapping` = `insentif`.`mapping_insentif`.`idmapping`)) join `insentif`.`barang_insentif` on(`insentif`.`mapping_insentif_detail`.`idbarang_insentif` = `insentif`.`barang_insentif`.`idbarang_insentif`)) join `insentif`.`barang` on(`insentif`.`barang_insentif`.`idbarang` = `insentif`.`barang`.`idbarang`))
mariadb-version=100411
